<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_Reservas_menuChart2</name>
   <tag></tag>
   <elementGuidId>f04fb120-b3a0-4abc-b1b9-1f6c44408639</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//canvas[@id='menuChart2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menuChart2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>7b7acfb0-1ee6-445d-8205-b25029c4dce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>16835d2c-7b0b-46b0-b5cb-e388a3656c50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>3ebb6933-9044-4f87-b5c6-6f991de0b6f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>prueba</value>
      <webElementGuid>9dbfbe70-8308-4f24-8a1a-637d2d3ee38f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menuChart2</value>
      <webElementGuid>62003efd-a317-47b4-b4e3-05878ba82fc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuChart2&quot;)</value>
      <webElementGuid>2580b8b8-b287-4141-b28e-3785d93cbf30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='menuChart2']</value>
      <webElementGuid>bb0b3ea6-af9b-4628-9d5b-d876c625c86a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/canvas</value>
      <webElementGuid>f8edb2cd-7475-4b7d-8247-46d876947304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = 'menuChart2']</value>
      <webElementGuid>b25bb62a-4d61-4a88-8f6b-f11144025c2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
