<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_Dolar Oficial Mayorista_menuChart4</name>
   <tag></tag>
   <elementGuidId>d60d2405-5fc3-4c8d-bb62-318322e3f6cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//canvas[@id='menuChart4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menuChart4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>275e2b98-6239-4aec-b81e-bbef1624c66f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>920da33c-8aff-48b7-b500-87b103b2b8cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>861cdf15-9cae-4aee-9567-dde2fad933cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>prueba</value>
      <webElementGuid>ab78182c-f5c6-4daf-9299-f69514b38d30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menuChart4</value>
      <webElementGuid>0345c4d1-d9fc-435e-8b68-27dfa798cc8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuChart4&quot;)</value>
      <webElementGuid>c490418a-7a82-428a-9810-0e412ac3f3b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='menuChart4']</value>
      <webElementGuid>ed32ba12-a6f7-4fae-a124-24b9a7b15cce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/canvas</value>
      <webElementGuid>ba6bcd7c-f762-4ad9-ab3e-9a982ddc9adc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = 'menuChart4']</value>
      <webElementGuid>ef845153-aba5-4457-9990-4ceb0706e6d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
