<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_Ajuste CER_chart</name>
   <tag></tag>
   <elementGuidId>a2073e05-7037-4b60-a949-d108d04cb975</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#chart</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//canvas[@id='chart']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#chart</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>a458cb82-35e2-4b71-a980-b225a7417436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chart</value>
      <webElementGuid>90d977b1-48e1-4a0d-8574-8f759063ce65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>982</value>
      <webElementGuid>43860f09-d69d-4f37-a19b-0ee685283fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>411</value>
      <webElementGuid>c5c9572b-3b15-400b-aff9-d062edfa66e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chart&quot;)</value>
      <webElementGuid>6b0874e5-558f-427e-9647-45e3bcbddc43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='chart']</value>
      <webElementGuid>9db504ff-7894-41b0-9f17-348db2fae955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ajuste CER'])[1]/following::canvas[1]</value>
      <webElementGuid>22f8cbb2-d693-45a9-b742-d71366d7d1e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='?'])[1]/following::canvas[1]</value>
      <webElementGuid>fb76a49f-b6f4-40b4-8371-234e2656dcf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fuente: BCRA'])[1]/preceding::canvas[1]</value>
      <webElementGuid>dd02413f-ae0d-4a9e-a3ff-c630ba4b81f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Volver'])[1]/preceding::canvas[1]</value>
      <webElementGuid>70b4c506-e790-43f6-a96d-c278c11d59f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>ffe0b538-5b9e-4bee-a1e8-d4dfbf2a6b68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = 'chart']</value>
      <webElementGuid>fad2ec10-2831-44c2-86bc-2274ac207501</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
