<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_INFLACIN ESPERADA PARA LOS PRXIMOS 12 M_9e45e9</name>
   <tag></tag>
   <elementGuidId>7eeaae50-7e05-4543-869a-bfe4783f3b49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='EconoVista']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b8df3b05-04ee-4f0d-88fd-71b2884e9f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/Logo.png</value>
      <webElementGuid>791faf79-88fb-4e66-a84d-8d26ca3fb48a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>EconoVista</value>
      <webElementGuid>9bdbd489-815b-49a4-a30a-b18fdacc31dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlink</name>
      <type>Main</type>
      <value>/</value>
      <webElementGuid>4507152d-555e-41f5-ae4a-7ffae01c6f2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>1446b6dd-3b5c-49af-b1b0-82409c9b7729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1bca2d9d-caa5-4979-b3bf-1c4e612ae10e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-router-link</name>
      <type>Main</type>
      <value>/</value>
      <webElementGuid>2ee9e234-862e-45a0-8cf3-880697341cae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/div[@class=&quot;contenedor&quot;]/app-header[@class=&quot;fila&quot;]/header[@class=&quot;contenedor-logo&quot;]/img[@class=&quot;icon&quot;]</value>
      <webElementGuid>af57698a-de67-4353-a78e-f6b34b0e67e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='EconoVista']</value>
      <webElementGuid>c8a19b1d-5490-4f34-bb81-b0a63a6a2b33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>4e1c9d6c-35d0-4b27-8183-1a78223faeda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/Logo.png' and @alt = 'EconoVista']</value>
      <webElementGuid>25c2354e-a8ed-402d-af44-e8b80e86c82e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
