<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_INFLACIN MENSUAL SEGN INDEC (VARIACIN E_fcbd1f</name>
   <tag></tag>
   <elementGuidId>fa757e0f-2437-42aa-bce3-e7ff5dc8acc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='EconoVista']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8003832e-40f9-4805-8ca8-c2c70cc79e55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/Logo.png</value>
      <webElementGuid>7f2ed697-acbe-46e9-af5c-2bfaaaec9d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>EconoVista</value>
      <webElementGuid>b34cc596-aa2a-42dc-8613-e7e4508ce2e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlink</name>
      <type>Main</type>
      <value>/</value>
      <webElementGuid>56cc95f7-33cf-472b-99ac-4e82e384ca0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>c1fe2058-bffb-4df8-b4fa-73e5e7a26a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e7e5fdc1-2ce4-4768-947c-d4c822609005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-router-link</name>
      <type>Main</type>
      <value>/</value>
      <webElementGuid>405fbd83-7f62-4e63-9be8-637f69159551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/div[@class=&quot;contenedor&quot;]/app-header[@class=&quot;fila&quot;]/header[@class=&quot;contenedor-logo&quot;]/img[@class=&quot;icon&quot;]</value>
      <webElementGuid>6ff29772-4eb2-42f3-9b9d-25b8a0619295</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='EconoVista']</value>
      <webElementGuid>8fb21fe7-a2a1-4d94-9960-c5e1f6bcdea7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>8c6021db-e0e8-4dbd-9a98-bf02f5d0762b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/Logo.png' and @alt = 'EconoVista']</value>
      <webElementGuid>63460aac-67f2-453d-96d6-d99480bc5fe9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
