<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_TIPO DE CAMBIO DE REFERENCIA MINORISTA_icon</name>
   <tag></tag>
   <elementGuidId>d9cd31b2-7142-4125-8f28-b7df395b7d25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='EconoVista']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;EconoVista&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e0bd0a5e-4f19-4e4d-96b3-a1fe42caae80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/Logo.png</value>
      <webElementGuid>592ae94d-05e6-46c7-9759-d6c76f7c453d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>EconoVista</value>
      <webElementGuid>ac250e86-e8a8-4e7a-a8f9-e9d192305d3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlink</name>
      <type>Main</type>
      <value>/</value>
      <webElementGuid>c302ce22-8754-4d0c-af82-a34b98b5e9b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>34bb2cc8-38be-4224-be23-47bd12543f2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>37e65e37-31dc-4854-bc78-d97b11b3398f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-router-link</name>
      <type>Main</type>
      <value>/</value>
      <webElementGuid>315ffdd0-e5bf-44ef-9a3a-33247e006c82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/div[@class=&quot;contenedor&quot;]/app-header[@class=&quot;fila&quot;]/header[@class=&quot;contenedor-logo&quot;]/img[@class=&quot;icon&quot;]</value>
      <webElementGuid>a3af42ae-55ad-4664-8e2b-9e63c93fc557</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='EconoVista']</value>
      <webElementGuid>d8d69852-ab65-4dc2-a20e-e83fa434e9ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>6910c1bb-4bee-4437-b33b-7724379c80e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/Logo.png' and @alt = 'EconoVista']</value>
      <webElementGuid>64c90752-fc7c-41e0-a2a6-eb3242cf3413</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
