<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Ajuste CER_mat-mdc-button-touch-target</name>
   <tag></tag>
   <elementGuidId>da6ec914-843b-4491-80da-6596db73e90d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ajuste-cer-btn > span.mat-mdc-button-touch-target</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ajuste-cer-btn']/span[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Ajuste CER&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>95814abf-ecb8-4f12-96a0-505d9e3f52d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-button-touch-target</value>
      <webElementGuid>f9962fb2-da23-4789-9e37-4f1afd0d0bcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ajuste-cer-btn&quot;)/span[@class=&quot;mat-mdc-button-touch-target&quot;]</value>
      <webElementGuid>75e5c6e5-8fb1-4f96-ac92-a2451ef336d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='ajuste-cer-btn']/span[4]</value>
      <webElementGuid>66365c86-af99-4348-9ad3-9b7c2b673717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button/span[4]</value>
      <webElementGuid>3b15a6b9-13c1-4daa-9eb1-c6069a607e2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
