<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Ajuste CER</name>
   <tag></tag>
   <elementGuidId>1fd3d8ab-0e1d-4bd1-b8aa-ebb7ad55e01d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ajuste-cer-btn > span.mdc-button__label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ajuste-cer-btn']/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Ajuste CER&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>de653ada-8ccf-4f37-809f-8daa085f43a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdc-button__label</value>
      <webElementGuid>737331c4-28f8-44c9-a2c8-6c914b28dfbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ajuste CER</value>
      <webElementGuid>227219a5-efd5-48fc-942f-657472f98e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ajuste-cer-btn&quot;)/span[@class=&quot;mdc-button__label&quot;]</value>
      <webElementGuid>b452099b-4428-40c7-9f22-84e996ea5d28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='ajuste-cer-btn']/span[2]</value>
      <webElementGuid>a7ebd1fb-731a-4c29-91ab-e209820671da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='?'])[1]/following::span[4]</value>
      <webElementGuid>4b1cf505-550f-4cbb-b042-b147cefc4632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Limpiar'])[1]/following::span[8]</value>
      <webElementGuid>f0b7318a-89d4-444d-a249-daffd2ac7d01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[object Object]'])[1]/preceding::span[4]</value>
      <webElementGuid>a9586cb6-1c73-4310-b4bd-151b3aa84b3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ajuste CER']/parent::*</value>
      <webElementGuid>51afe95a-2345-4eb3-97d5-4d1576922d8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button/span[2]</value>
      <webElementGuid>85265521-32d3-4839-a33d-b9e0d5cf2eb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Ajuste CER' or . = 'Ajuste CER')]</value>
      <webElementGuid>8f9a9eb9-55ad-4945-b9f3-595accc3b37c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fuente: BCRA'])[1]/preceding::span[4]</value>
      <webElementGuid>ec840da0-b6c4-45b4-96f1-ea5d8768cc63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Volver'])[1]/preceding::span[5]</value>
      <webElementGuid>b7f5fb08-59c7-49e1-8ebc-ac08aee8c491</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
